#!/bin/sh /etc/rc.common

START=99

start() {
sleep 10
frpnum=$(echo "$(ifconfig eth0 | grep "HWaddr" | awk '{print $5}')" | tr 'A-Z' 'a-z' | tr -d ":")
uci set frp.@proxy[0].remark=$frpnum
uci set frp.@proxy[0].subdomain=$frpnum
uci commit frp

/etc/init.d/frp restart
rm -rf /etc/config/passwall_show
}
