#!/bin/sh

uci -q batch <<-EOF
    set luci.main.lang=zh_cn
    set luci.main.mediaurlbase=/luci-static/argon
    commit luci

    set system.@system[0].hostname=Router
    set system.@system[0].timezone=CST-8
    set system.@system[0].zonename=Asia/Shanghai
    commit system

    set network.lan.ipaddr=192.168.123.1
    commit network
EOF

sed -i 's/root:::0:99999:7:::/root:$1$.jRW0wfC$K2zXyaQ5S9cX3bG8H7NJ81:0:0:99999:7:::/g' /etc/shadow

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R8.3.19.0410'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Router'" >> /etc/openwrt_release

chmod 0755 /etc/init.d/*

rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache*

exit 0
