#!/bin/sh /etc/rc.common

START=99

start() {
    sleep 10

    frpnum=$(ifconfig br-lan | grep "HWaddr" | awk '{print $5}' | tr 'A-Z' 'a-z' | tr -d ":")
    uci set frpc.web.name=$frpnum
    uci set frpc.web.subdomain=$frpnum
    uci commit frpc

    uci set passwall.@global[0].hide_from_luci=1
    uci commit passwall
    rm -rf /tmp/luci-*
    /etc/init.d/rpcd restart >/dev/null
}
