#!/bin/sh /etc/rc.common

START=99

start() {
    sleep 10

    frpnum=$(echo "$(ifconfig br-lan | grep "HWaddr" | awk '{print $5}')" | tr 'A-Z' 'a-z' | tr -d ":")
    uci set frpc.web.name=$frpnum
    uci set frpc.web.subdomain=$frpnum
    uci commit frpc

    if ping -c 3 -W 5 frp.ydns.xyz >/dev/null 2>&1; then
        uci set frpc.common.server_addr='frp.ydns.xyz'
        uci commit frpc
        /etc/init.d/frpc restart
        logger "FRP service started with ID: $frpnum (ydns reachable)"
    else
    if ping -c 3 -W 5 frp.201088.xyz >/dev/null 2>&1; then
        uci set frpc.common.server_addr='frp.201088.xyz'
        uci commit frpc
        /etc/init.d/frpc restart
        logger "FRP service started with ID: $frpnum (201088 reachable)"
    else
        /etc/init.d/frpc stop
        logger "FRP service stopped due to network unreachable"
        fi
    fi

    uci set passwall.@global[0].hide_from_luci=1
    uci commit passwall
    rm -rf /tmp/luci-*
    /etc/init.d/rpcd restart >/dev/null
}
