#!/bin/sh /etc/rc.common

START=99

start() {
sleep 10
frpnum=$(echo "$(ifconfig br-lan | grep "HWaddr" | awk '{print $5}')" | tr 'A-Z' 'a-z' | tr -d ":")
uci set frpc.ssh.name=$frpnum
uci set frpc.ssh.subdomain=$frpnum
uci commit frpc

/etc/init.d/frpc restart
rm -rf /etc/config/passwall_show
rm -rf /etc/config/autoupdate_show
uci set passwall.@global[0].hide_from_luci=1
}
