#!/bin/sh

uci set luci.main.lang=zh_cn
uci set luci.main.mediaurlbase=/luci-static/argon
uci commit luci

uci set system.@system[0].hostname=Router
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set network.lan.ipaddr=192.168.123.1
uci commit network

sed -i 's/root::0:0:99999:7:::/root:$1$.jRW0wfC$K2zXyaQ5S9cX3bG8H7NJ81:0:0:99999:7:::/g' /etc/shadow
sed -i 's/root:::0:99999:7:::/root:$1$.jRW0wfC$K2zXyaQ5S9cX3bG8H7NJ81:0:0:99999:7:::/g' /etc/shadow
#root:$1$RQytXiRO$uOrT4VYZL.2qzRNaI.IXz.:19675:0:99999:7:::  #lxw
#root:$1$oA/Yj6wt$pcG.PiYcTqrA3W8a6Kw9l/:19783:0:99999:7:::  #psw

sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='R8.3.19.0410'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='Router'" >> /etc/openwrt_release

chmod 0755 /etc/init.d/*

rm -rf /tmp/luci-modulecache
rm -f /tmp/luci-indexcache*

exit 0
